name = "nativefragments-demo-form-wizard"
main = "worker.js"
compatibility_date = "2026-06-01"
routes = [
  { pattern = "form-wizard.nativefragments.org", custom_domain = true }
]

[assets]
directory = "./public"
binding = "ASSETS"
