name = "nativefragments-signal-counter"
main = "worker.js"
compatibility_date = "2026-06-01"
routes = [
  { pattern = "signal-counter.nativefragments.org", custom_domain = true }
]

[assets]
directory = "./public"
binding = "ASSETS"
